# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# This project uses Conventional Commits for PR titles and commit messages
# CodeRabbit configuration for pharmhand R package
# Docs: https://docs.coderabbit.ai/getting-started/configure-coderabbit

language: en-US

reviews:
  # Use assertive profile for thorough code review
  profile: assertive

  # Don't auto-approve - we want manual approval
  request_changes_workflow: false

  # Include high-level summary in PR description
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"

  # Walkthrough options
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: false  # Not very useful for R code
  assess_linked_issues: true
  related_issues: true
  related_prs: true

  # Disable some noise
  poem: false
  suggested_labels: false
  suggested_reviewers: false

  # Estimate review effort - useful for planning
  estimate_code_review_effort: true

  # Path filters - exclude generated files
  path_filters:
    - "!man/**"           # Generated documentation
    - "!NAMESPACE"        # Generated by roxygen2
    - "!docs/**"          # pkgdown site
    - "!*.Rproj"          # RStudio project file
    - "!.Rbuildignore"
    - "!.gitignore"

  # R package specific review instructions
  path_instructions:
    - path: "R/**/*.R"
      instructions: |
        This is an R package following tidyverse style. Review for:
        - roxygen2 documentation completeness (@param, @return, @examples, @export)
        - S7 class usage (not S3/S4/R6)
        - Use of rlang for error handling (ph_abort, ph_warn, ph_inform)
        - Consistent use of dplyr verbs and tidyverse patterns
        - Proper use of .data pronoun in dplyr pipelines
        - No use of <<- or global assignment
        - Functions should be pure where possible

    - path: "tests/testthat/**/*.R"
      instructions: |
        Test files using testthat 3.x. Review for:
        - Descriptive test_that() descriptions (under 80 chars)
        - One assertion concept per test where practical
        - Use of expect_* functions (not stopifnot)
        - Proper use of fixtures from helper-fixtures.R
        - No reliance on external state or network
        - Tests should be deterministic

    - path: "vignettes/**/*.Rmd"
      instructions: |
        R Markdown vignettes. Review for:
        - Working code examples (eval=TRUE where possible)
        - Clear explanations for clinical/HTA audience
        - Consistent formatting with other vignettes
        - Proper cross-references to function documentation

    - path: "DESCRIPTION"
      instructions: |
        R package DESCRIPTION file. Check:
        - Version follows semantic versioning
        - All dependencies have minimum versions if needed
        - No circular dependencies
        - Suggests vs Imports is appropriate

    - path: "NEWS.md"
      instructions: |
        Changelog file. Ensure:
        - New features/fixes are documented under correct version
        - Breaking changes are clearly marked
        - Issue/PR references included where applicable

  # Auto-review settings
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "draft"
    base_branches:
      - "main"
      - "dev"

  # Finishing touches
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

  # Pre-merge checks
  pre_merge_checks:
    title:
      mode: warning
      requirements: |
        PR titles MUST follow Conventional Commits 1.0.0 (https://conventionalcommits.org):
        
        Format: <type>[optional scope]: <description>
        
        Types (required):
        - feat: new feature (correlates with MINOR in SemVer)
        - fix: bug fix (correlates with PATCH in SemVer)
        
        Additional types (recommended):
        - docs: documentation only changes
        - style: formatting, white-space, etc. (no code change)
        - refactor: code change that neither fixes a bug nor adds a feature
        - perf: performance improvement
        - test: adding or updating tests
        - build: changes to build system or dependencies
        - ci: changes to CI configuration
        - chore: other changes that don't modify src or test files
        - revert: reverts a previous commit
        
        Breaking changes:
        - Add ! after type/scope: feat!: or feat(scope)!:
        - Or add BREAKING CHANGE: footer in PR description
        
        Scope (optional): noun in parentheses describing section of codebase
        Examples: feat(meta): ..., fix(safety): ..., docs(vignette): ...
        
        Description: imperative mood, lowercase, no period at end
    description:
      mode: warning
    docstrings:
      mode: off  # Using roxygen2 instead

  # Tool configuration
  tools:
    # Disable tools not relevant for R
    ruff:
      enabled: false
    biome:
      enabled: false
    eslint:
      enabled: false
    phpstan:
      enabled: false
    golangci-lint:
      enabled: false
    detekt:
      enabled: false
    rubocop:
      enabled: false
    swiftlint:
      enabled: false
    buf:
      enabled: false
    pmd:
      enabled: false
    cppcheck:
      enabled: false
    clippy:
      enabled: false
    flake8:
      enabled: false
    pylint:
      enabled: false
    oxc:
      enabled: false
    prismaLint:
      enabled: false
    shopifyThemeCheck:
      enabled: false
    sqlfluff:
      enabled: false
    checkov:
      enabled: false
    hadolint:
      enabled: false
    circleci:
      enabled: false
    fortitudeLint:
      enabled: false
    luacheck:
      enabled: false
    brakeman:
      enabled: false
    dotenvLint:
      enabled: false
    htmlhint:
      enabled: false
    checkmake:
      enabled: false

    # Keep useful tools
    shellcheck:
      enabled: true  # For any shell scripts
    markdownlint:
      enabled: true  # For README, NEWS, vignettes
    yamllint:
      enabled: true  # For YAML configs
    languagetool:
      enabled: true
      level: default
    gitleaks:
      enabled: true  # Security scanning
    actionlint:
      enabled: true  # GitHub Actions
    github-checks:
      enabled: true
      timeout_ms: 120000  # 2 minutes for R CMD check

chat:
  auto_reply: true
  art: false

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  learnings:
    scope: local
  issues:
    scope: local
  pull_requests:
    scope: local
